#!/usr/bin/env -S ansible-playbook -i inventory
---

# This is an example playbook for using the podman-pihole role from Geekoops
# Adjust the variables to you needs and set an appropriate inventory file

- name: Install pihole podman service
  hosts: all

  roles:
    - role: podman-pihole
      vars:
        pihole_password: 'nots3cr3t'
        pihole_publish:
          - '53:53/udp'
          - '[::]:53:53/udp'
          - '53:53/tcp'
          - '[::]:53:53/tcp'
          - '127.0.0.1:80:80/tcp'
